### ISSUE TITLE
Экран добавления: отображение станций и поиск

### ISSUE THREAD

**Issue by otsheln1k** [moevm/adfmp1h22-player#13]
Вроде был какой-то SearchView, который можно как-за заставить что-то делать с RecyclerView. Надо выяснить.

Чуть-чуть надо привести в порядок список станций (например, вынести ли разметку элемента списка в отдельный ресурс, чтобы не было пересечения со StationListFragment; ещё сделать отступы).

**Comment by otsheln1k** [comment]
Для подробного поиска можно сделать действие в меню, которое открывает браузер с radio-browser.org.

**Comment by Eldar1999** [comment]
Done
