### ISSUE TITLE
Кэширование фавиконов

### ISSUE THREAD

**Issue by otsheln1k** [moevm/adfmp1h22-player#15]
- Видим URL фавиконки (например, когда открываем список добавленных станций на главном экране)
- Пробиваем URL по БД, можем найти имя файла и дату скачивания
- Если дата слишком старая (например, старше пары дней) удаляем файл и выполняем повторное скачивание
- Если записи нет, просто скачиваем
- Если запись станции в каталоге обновляется, в любом случае скачиваем по новой (или можно смотреть именно по изменению URL, короче думать надо)
- При скачивании задаём рандомное имя файла (например, генерим UUID) и добавляем запись в БД

**Comment by Eldar1999** [comment]
Done
