### ISSUE TITLE
UI на заглушках: Экран добавления станции

### ISSUE THREAD

**Issue by otsheln1k** [moevm/adfmp1h22-player#3]
При нажатии на пункт списка переключается фейковое воспроизведение (при воспроизведении иконка станции заменяется на "остановить"). При нажатии на кнопку на пункте списка происходит фейковое добавление/удаление из списка станций пользователя (если станция не добавлена, на кнопке стоит иконка "добавить", а если уже добавлена то "убрать").

См. [макет](https://github.com/moevm/adfmp1h22-player/wiki/Mockup)

**Comment by Eldar1999** [comment]
Необходима проверка
